/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.92
 * Generated at: 2023-11-01 10:57:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"welcome.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: black\">\r\n");
      out.write("	<!-- data are not stored -->\r\n");
      out.write("	");

	response.setHeader("Cache-Control", "no-cache, no-store,must-revalidate");
	if (session.getAttribute("email") == null) {
		response.sendRedirect("login.jsp");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--header  -->\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li class=\"active\"><a href=\"#\"><b>Aress Software & Education Technologies</b></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <form action=\"Logout\">\r\n");
      out.write("                    <button class=\"btn btn-danger navbar-btn\">Logout</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!--welcome image  -->\r\n");
      out.write("	<center>\r\n");
      out.write("		<h2 class=\"animated fadeIn delay-1s h2\">\r\n");
      out.write("			<b> Welcome to Aress Software & Education Technologies</b>\r\n");
      out.write("		</h2>\r\n");
      out.write("	</center>\r\n");
      out.write("\r\n");
      out.write("	<center>\r\n");
      out.write("		<h5>\r\n");
      out.write("			<b>Employee Database</b>\r\n");
      out.write("		</h5>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- First Row -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://images.pexels.com/photos/374598/pexels-photo-374598.jpeg?auto=compress&cs=tinysrgb&w=600\"\r\n");
      out.write("						class=\"img-responsive img-thumbnail img-zoom\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://images.pexels.com/photos/2041627/pexels-photo-2041627.jpeg?auto=compress&cs=tinysrgb&w=600\"\r\n");
      out.write("						class=\"img-responsive img-thumbnail img-zoom\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=600\"\r\n");
      out.write("						class=\"img-responsive img-thumbnail img-zoom\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Second Row -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?auto=compress&cs=tinysrgb&w=600\"\r\n");
      out.write("						class=\"img-responsive img-thumbnail img-zoom\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://images.pexels.com/photos/9998331/pexels-photo-9998331.jpeg?auto=compress&cs=tinysrgb&w=600\"\r\n");
      out.write("						class=\"img-responsive img-thumbnail img-zoom\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://images.pexels.com/photos/3184639/pexels-photo-3184639.jpeg?auto=compress&cs=tinysrgb&w=600\"\r\n");
      out.write("						class=\"img-responsive img-thumbnail img-zoom\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- display data on JSP with error handling -->\r\n");
      out.write("	<center>\r\n");
      out.write("		<table border=\"2\" style=\"width:80%\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>Sr.</th>\r\n");
      out.write("				<th>First Name</th>\r\n");
      out.write("				<th>Last Name</th>\r\n");
      out.write("				<th>Email</th>\r\n");
      out.write("				<th>Age</th>\r\n");
      out.write("				<th>Gender</th>\r\n");
      out.write("				<th>Address</th>\r\n");
      out.write("				<th>City</th>\r\n");
      out.write("				<th>State</th>\r\n");
      out.write("				<th>Postal Code</th>\r\n");
      out.write("				<th>Phone Number</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			Connection conn = null;
			Statement st = null;
			ResultSet rs = null;
			try {
				Class.forName("com.mysql.jdbc.Driver");
				conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/shree", "root", "mysql@2002");
				st = conn.createStatement();
				String query = "select* from homeData";
				rs = st.executeQuery(query);
				while (rs.next()) {
			
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(7));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(8));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(9));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(10));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(rs.getString(11));
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			}
			} catch (Exception e) {
			}
			
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</center>\r\n");
      out.write("\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<b>All Copyright Reserved</b> <i class=\"fas fa-copyright\"></i>\r\n");
      out.write("	</div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
