/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.92
 * Generated at: 2023-10-27 11:15:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class validation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lato&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link href=\"validate.js\">\r\n");
      out.write("    <style>\r\n");
      out.write("      body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0\r\n");
      out.write("      }\r\n");
      out.write("      * {\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      }\r\n");
      out.write("      .container,\r\n");
      out.write("      .form-box {\r\n");
      out.write("      display: block;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      body {\r\n");
      out.write("      background: #1a9ae2;\r\n");
      out.write("      font-family: 'Lato', sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box {\r\n");
      out.write("      max-width: 350px;\r\n");
      out.write("      margin: 20px auto;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      min-height: 200px;\r\n");
      out.write("      padding: 30px;\r\n");
      out.write("      background: #fff;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box .input-field {\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box input {\r\n");
      out.write("      display: block;\r\n");
      out.write("      min-height: 20px;\r\n");
      out.write("      font-size: 18px;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      border: 1px solid #ccc;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box input[type='text'] {\r\n");
      out.write("      padding-right: 25px\r\n");
      out.write("      }\r\n");
      out.write("      .form-box h2 {\r\n");
      out.write("      display: block;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 28px;\r\n");
      out.write("      margin-bottom: 40px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box label {\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      color: #000000;\r\n");
      out.write("      margin-bottom: 5px;\r\n");
      out.write("      display: block;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box input[type='submit'] {\r\n");
      out.write("      background: #1a9ae2;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box .fa {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      right: 10px;\r\n");
      out.write("      margin-top: -30px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box .input-field.error input {\r\n");
      out.write("      border-color: #f00;\r\n");
      out.write("      border-width: 2px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box .input-field.error .fa {\r\n");
      out.write("      color: #f00;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box .input-field.success input {\r\n");
      out.write("      border-color: #0b0;\r\n");
      out.write("      border-width: 2px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-box .input-field.success .fa {\r\n");
      out.write("      color: #0b0;\r\n");
      out.write("      }\r\n");
      out.write("      .input-field span {\r\n");
      out.write("      display: none;\r\n");
      out.write("      }\r\n");
      out.write("      .input-field.error span {\r\n");
      out.write("      color: #f00;\r\n");
      out.write("      display: block\r\n");
      out.write("      }\r\n");
      out.write("      .input-field.success span {\r\n");
      out.write("      color: #0b0;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"form-box\">\r\n");
      out.write("        <h2>Create Your Account</h2>\r\n");
      out.write("        <div class=\"input-field\">\r\n");
      out.write("          <label for=\"\">Username</label>\r\n");
      out.write("          <input type=\"text\" id=\"username\" placeholder=\"username\">\r\n");
      out.write("          <i class=\"fa \" aria-hidden=\"true\"></i>\r\n");
      out.write("          <span></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-field\">\r\n");
      out.write("          <label for=\"\">Email</label>\r\n");
      out.write("          <input type=\"text\" id=\"email\" placeholder=\"email address\">\r\n");
      out.write("          <i class=\"fa \" aria-hidden=\"true\"></i>\r\n");
      out.write("          <span></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-field\">\r\n");
      out.write("          <label for=\"\">Password</label>\r\n");
      out.write("          <input type=\"text\" id=\"pass1\" placeholder=\"password\">\r\n");
      out.write("          <i class=\"fa \" aria-hidden=\"true\"></i>\r\n");
      out.write("          <span></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-field\">\r\n");
      out.write("          <label for=\"\">Confirm Password</label>\r\n");
      out.write("          <input type=\"text\" id=\"pass2\" placeholder=\"confirm password\">\r\n");
      out.write("          <i class=\"fa \" aria-hidden=\"true\"></i>\r\n");
      out.write("          <span></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"submit\" id=\"submit\" value=\"Submit\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
